### ISSUE TITLE
BlazorGridAndReport does not work out of the box.

### ISSUE THREAD

**Issue by bholland314** [telerik/reporting-samples#56]
I am a trial user for Telerik Reporting and I am a user of Blazor UI. 
I tried to run the reporting-samples/BlazorGridAndReportViewer.
First problem the Dependency Packages are wrong. They don't list the trial versions. Had to figure that out on my own that there are trial versions of nuget packages. Didn't see that in any documentation. Project doesn't come with a readme file.
Second problem, after I got the packages all sorted out, tried running the application. Going to the Report tab produces
"An unhandled exeption has occured."

Here is the error in the Console.
[2022-05-12T22:09:15.753Z] Error: Microsoft.JSInterop.JSException: Could not find 'telerikReportViewerInterop.createReportViewerWidget' ('telerikReportViewerInterop' was undefined).
Error: Could not find 'telerikReportViewerInterop.createReportViewerWidget' ('telerikReportViewerInterop' was undefined).
    at https://localhost:44378/blazor-reporting/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://localhost:44378/blazor-reporting/_framework/blazor.server.js:1:465)
    at E (https://localhost:44378/blazor-reporting/_framework/blazor.server.js:1:2606)
    at https://localhost:44378/blazor-reporting/_framework/blazor.server.js:1:3494
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:44378/blazor-reporting/_framework/blazor.server.js:1:3475)
    at https://localhost:44378/blazor-reporting/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:44378/blazor-reporting/_framework/blazor.server.js:1:71987)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by nelci592** [comment]
Hi Brian,
I am sorry to hear that you experienced issues while testing the demo. I was able to reproduce the issue. When you are using trial packages, some of the references have to be changed. For example, for Telerik Reporting:
`<script src="_content/Telerik.ReportViewer.Blazor/interop.js" defer /script>
@* Or this one if using the Telerik.ReportViewer.Blazor.Trial package *@
@*<script src="_content/Telerik.ReportViewer.Blazor.Trial/interop.js" defer /script>*@`
Please, find more details in the [How to Use Blazor Report Viewer](https://docs.telerik.com/reporting/using-reports-in-applications/display-reports-in-applications/web-application/blazor-report-viewer/how-to-use-blazor-report-viewer#how-to-use-blazor-report-viewer) article. 
Also, you need to make the following changes for Telerik UI for Blazor:
` @* For Blazor UI *@
    <script src="_content/Telerik.UI.for.Blazor.Trial/js/telerik-blazor.js" defer></script>
    <link rel="stylesheet" href="_content/Telerik.UI.for.Blazor.Trial/css/kendo-theme-default/all.css" />`
I hope this information will help you. Please, make the following changes and let us know how it goes.
